name: Backend cd workflow

on:
  push:
    branches:
      - main

  workflow_dispatch:
env:
  PYTHON_VERSION: '3.10'

jobs:
  install-build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Use Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install pipenv
      run: |
        cd backend
        pip install pipenv

    - name: Install dependencies
      run: |
        cd backend
        pipenv install --dev

    - name: Run Lint
      run: |
        cd backend
        pipenv run flake8 .
    
    - name: Run Test
      run: |
        cd backend
        pipenv run pytest

    - name: Build
      env:
        REPOSITORY: movie-picture-be
        IMAGE_TAG: latest
      run: |
        cd backend
        docker build --tag $REPOSITORY:$IMAGE_TAG .

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: install-build-test

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Use Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install pipenv
      run: |
        cd backend
        pip install pipenv

    - name: Install dependencies
      run: |
        cd backend
        pipenv install --dev

    - name: Build
      env:
        REPOSITORY: movie-picture-be
        IMAGE_TAG: latest
      run: |
        cd backend
        docker build -t $REPOSITORY .
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Get images
      run: docker images

    - name: Tag image
      env:
        REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
        REPOSITORY: movie-picture-be
        IMAGE_TAG: latest
      run: docker tag $REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: Push docker image to Amazon ECR
      env:
        REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
        REPOSITORY: movie-picture-be
        IMAGE_TAG: latest
      run: docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: [install-build-test, build-and-push-image]

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Use kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Config for EKS cluster
      env:
        REGION: ${{ secrets.AWS_REGION }}
        CLUSTER_NAME: my-cluster
      run: |
        aws eks update-kubeconfig --region $REGION --name $CLUSTER_NAME
      
    - name: Check folder
      run: ls
      
    - name: Deploy application to EKS
      run: |
        cd backend/k8s
        ls
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
    - name: Check deploy
      run: |
        kubectl get deployment
        kubectl get pods