name: Frontend ci workflow

on:
  pull_request:
    branches:
      - main
      
  workflow_dispatch:
env:
  NODE_VERSION: '18.x'

jobs:
  lint-job:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: |
        cd frontend
        npm ci

    - name: Run Lint
      run: |
        cd frontend
        npm run lint
  
  test-job:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: |
        cd frontend
        npm ci

    - name: Run Test
      run: |
        cd frontend
        npm run test

  build-job:
    needs: [lint-job, test-job]
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: |
        cd frontend
        npm ci

    - name: Run Test
      run: |
        cd frontend
        npm run test